name: Merge any release branch
on:
  push:
    branches:
      - '*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge now -> main
        uses:  actions/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}

  close-issue:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.head_commit.message, 'HU') 
        name: Close Issue
        uses:  actions/close-issue@v2
        with:
          comment: |
            El mensaje contine HU.
            Auto-closing this issue.
